name       : libconfig
version    : 1.7.2
release    : 4
source     :
    - https://github.com/hyperrealm/libconfig/archive/v1.7.2.tar.gz : f67ac44099916ae260a6c9e290a90809e7d782d96cdd462cac656ebc5b685726
license    : LGPL-3.1
component  : programming.library
clang      : no
summary    : Libconfig is a simple library for processing structured configuration
    files
description: |
    Libconfig is a simple library for processing structured configuration files
builddeps  :
    - libgcc
    - texinfo
libsplit   : no
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test

