name       : libconfig
version    : 1.5
release    : 1
source     :
    - http://hyperrealm.com/libconfig/libconfig-1.5.tar.gz : e31daa390d8e4461c8830512fe2e13ba1a3d6a02a2305a02429eec61e68703f6
license    : LGPL-3.0
summary    : Libconfig is a simple library for processing structured configuration files
description: |
    Libconfig is a simple library for processing structured configuration files
clang : no
builddeps  :
    - libgcc
    - texinfo
libsplit : no
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
